### ISSUE TITLE
Final review typos

### ISSUE THREAD

**Issue by manon643** [EricDarve/numerical_linear_algebra#109]
Spotted a few typos while reading the review material for the final:

- p14 section 6.1.2 equation should be \sum_1^p
- p17 section 7.2.1 evals ordering is wrong
- p17 section 7.2.1 equation should be \lambda_1^k z^T x_1 x_1
- p17 section 7.2.2 missing two subscripts in \lambda_i 
- p17 section 7.2.2 algo 4 mu and ev are inverted 
- p17/18 Algo 4, 5 and 6 have random number of iterations and some missing subscripts (e_v)

Sorry if those were spotted before. 

Best,

**Comment by EricDarve** [comment]
Awesome. Thank you. Yes, the writing is pretty rough in places.

> p17 section 7.2.1 equation should be \lambda_1^k z^T x_1 x_1

There is an error here but it's not z^T x1. It's z^T y where y corresponds to X^{-1}.

> p17/18 Algo 4, 5 and 6 have random number of iterations and some missing subscripts (e_v)

I made those code variables instead of mathematical variables.
