### ISSUE TITLE
a couple typos and clarifications

### ISSUE THREAD

**Issue by amurphhh** [EricDarve/numerical_linear_algebra#110]
Page 177 - (second line) approximation spelled incorrectly.
Page 243 - (in the Arnoldi code) H = zeros(kmax, kmax) is declared twice.
Page 250 - (in number 1.) the 'three' \lambda I? Should the 'three' be there?
Page 261 - (3rd paragraph from the bottom) smaller 'than' not 'then'
Page 279 - (First paragraph in Section 5) "Here's we'll see." Should be "Here we'll see"
Page 354 - (Second paragraph) Entries below can skipped - need 'be'. 
Page 357 - (First paragraph after the code snippet) "The example matrix is the one ______ in this chapter above." Should be used instead of use.

**Comment by EricDarve** [comment]
Thank you for all these corrections. Very detailed work.

> Page 250 - (in number 1.) the 'three' \lambda I? Should the 'three' be there?

I rewrote this. It's a short explanation but hopefully clear. This is kind of a minor point.
