### ISSUE TITLE
CSC to CSR Pseudocode Typo

### ISSUE THREAD

**Issue by its-gucci** [EricDarve/numerical_linear_algebra#112]
On page 51 of the PDF version of the Course Reader (actual page 343 in the textbook), in the pseudocode for converting CSC to CSR, the lines 

colval = Vector{Int}(rowptr[end])
nzval = Vector{Float64}(rowptr[end])

should actually read 

colval = Vector{Int}(rowptr[end] - 1)
nzval = Vector{Float64}(rowptr[end] - 1)

Since rowptr[end] = Ap[end] = 1 more than the size of Ax, but colval, nzval should be exactly the size of Ax.

**Comment by EricDarve** [comment]
Yes. Correct. Very good catch.

**Comment by EricDarve** [comment]
What's your name on gradescope?

**Comment by its-gucci** [comment]
Hi Prof. Darve, I'm Jeffrey Gu (jeffgu@stanford.edu) on gradescope. Thanks
