### ISSUE TITLE
Not a mistake

### ISSUE THREAD

**Issue by QiuyeJia** [EricDarve/numerical_linear_algebra#115]
It's not a typo of the book. It's an observation started from the review session on Wednesday. During the review, Gnanasekaran took the (truncated version) of the graph in page 355 of the course reader. Then from the elimination tree, the status of 1 and 4 seems to be symmetric to 7. But we see that l_{71} is nonzero while l_{74} is zero. So we can not recover the sparsity of L itself from the elimination tree. We can only recover the reach.

However, if we look at the row subtrees, we can see that they completely reveal the sparsity pattern of L(if we take the union).

I was confused at first about this phenomenon, and I guess other readers might have the same confusion, or did not realize that the reach of the elimination tree is actually larger than the sparsity pattern of L.

**Comment by ghuba** [comment]
I think you are making a mistake here. The reach of the elimination tree exactly gives you the sparsity of L.

To get the sparsity of L, pick some row k. Take all i < k, a_{ik} \neq 0, take the reach of i going up in the etree until you reach node k. That's the sparsity of row k in L. 

The etree has all the information you need.

**Comment by EricDarve** [comment]
I think you are making a mistake here. The reach of the elimination tree exactly gives you the sparsity of L.

To get the sparsity of L, pick some row k. Take all i < k, a_{ik} \neq 0, take the reach of i going up in the etree until you reach node k. That's the sparsity of row k in L.

The etree has all the information you need.

**Comment by QiuyeJia** [comment]
>           I think you are making a mistake here. The reach of the elimination tree exactly gives you the sparsity of L.
> To get the sparsity of L, pick some row k. Take all i < k, a_{ik} \neq 0, take the reach of i going up in the etree until you reach node k. That's the sparsity of row k in L.
> The etree has all the information you need.

Yes, but just as you said, we need to ` Take all i < k, a_{ik} \neq 0 ' and this information is not encoded in the graph. However, what a_{ik} \neq 0 is encoded in the row subtree. That is what I what to say.


If we have the elimination tree, we still need the original sparsity of A to recover the sparsity pattern of L. Just as the example I quoted, node 4 and note 1 has no difference to the sparsity pattern of row 7, whereas the resulting l_{74} and l_{71} are different. If you only look at the elimination tree without knowing the sparsity pattern of A, you can not know whether l_{74} should be 0 or not.

**Comment by EricDarve** [comment]
I see your point. Yes, you can have different As and Ls that lead to the same elimination tree. That's correct. There is not a one-to-one relationship.

The row-subtree on the other hand completely determines the sparsity of the row.

**Comment by EricDarve** [comment]
I added a remark on p. 357 with a few examples related to your point.
