### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by nsaad31** [EricDarve/numerical_linear_algebra#116]
I'm writing to ask about 2 issues in the course reader.

1) The first one is on page 276 (page 284 in the pdf). In the proof of the equivalence, it's written       
 det (Gw- lamda I) =  det(term + radical(lamda) L + lamda^(-1/2) U).
My question is whether the numerator of the first term in the second determinant should be the additive inverse that is, (1 - w - lamda)I . Then, similarly, the sentence that follows:

"Thus,  is an eigenvalue of Gw if and only if ...  " , whether the numerator should be (w + lamda -1) I.

2) The second one is on page 281 (page 289 in the pdf). Right after the blue box of the Chebyshev semi-iterative method, there is this sentence:
"Then our expression for the error becomes:
e(k) = .."
In the second equality, in the first factor, the subscript of  is k, but shouldn't it be k-1 ? (That would also be consistent with the choice of qk).

Thank you so much and sorry for any kind of disturbance.
Best regards,
Nadim

**Comment by EricDarve** [comment]
The first one is on page 276 (page 284 in the pdf). In the proof of the equivalence, it's written
det (Gw- lamda I) = det(term + radical(lamda) L + lamda^(-1/2) U).
My question is whether the numerator of the first term in the second determinant should be the additive inverse that is, (1 - w - lambda)I . Then, similarly, the sentence that follows:
"Thus, is an eigenvalue of Gw if and only if ... " , whether the numerator should be (w + lambda -1) I.

You are right. I made a correction on these equations and left this error.

Let me know if you agree with the new version.

In the second equality, in the first factor, the subscript of is k, but shouldn't it be k-1 ? (That would also be consistent with the choice of qk).

Yes, k-1. You are correct.

**Comment by nsaad31** [comment]
Yes I agree with this one. Thank you Sir !
