### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by izabelaguiar** [EricDarve/numerical_linear_algebra#123]
The first bullet point on p38 reads "Diagonal matrices, which have _matrices_ only on the diagonal." I know this is true for block diagonal matrices, but since the topic is being introduced for regular matrices, I believe this should read "Diagonal matrices, which have _entries_ only on the diagonal."

**Comment by EricDarve** [comment]
Yes. It should be "non-zero entries." Thanks for the correction.
