### ISSUE TITLE
Typo page 33

### ISSUE THREAD

**Issue by jmhb1** [EricDarve/numerical_linear_algebra#125]
Section 3.9, page 33

> They are very easy to compute with accurately, making them the favorite tool of the numerical analyst

Should delete 'with' or change 'accurately' to 'accuracy'.

**Comment by EricDarve** [comment]
The grammar is twisted but this is correct. These matrices are easy to compute with, and when computing with them, we are very accurate. with is attached to compute (verb particle). accurately is the adverb.
