### ISSUE TITLE
Possible typo page 21

### ISSUE THREAD

**Issue by jayantmukho** [EricDarve/numerical_linear_algebra#128]
In the paragraph with the definition of **span** on Page 21 (page 11 of the reader), I think there is a typo. It reads:

> Notice that the span of x_1, ..., x_k is a subspace of R^n. We will denote this subspace as span{x_1, ..., x_n}

I think that last part should be span{x_1, ..., x_k}, if I am not mistaken

**Comment by EricDarve** [comment]
Thanks. Fixed.

I cannot assign you points. Are you on gradescope?

**Comment by jayantmukho** [comment]
Sorry, added the course late. I am on it now
