### ISSUE TITLE
QR decompostition question comes before QR definition

### ISSUE THREAD

**Issue by salliewalecka** [EricDarve/numerical_linear_algebra#130]
You have Problem 5 on pg 63 which has to do with the QR factorization, but you haven't yet introduced what the QR decomposition is.  Maybe that question should be moved to the next section or have a TLDR of what a QR decomposition is.

**Comment by EricDarve** [comment]
Yes you are right. I am going to add a short summary of what QR is. In principle the later section focuses on the algorithm to compute QR, not the properties of QR itself. You can do this problem if you just know that Q is orthogonal and R is upper triangular.
