### ISSUE TITLE
Thm 4.1 Proof: small nitpick

### ISSUE THREAD

**Issue by jsrozner** [EricDarve/numerical_linear_algebra#131]
In this proof, we use the fact that abs((xj)/(xi)) <= 1 since we have chosen the the component xi "that is the largest in x". 

Technically we need the component that has maximum abs value, otherwise in an all negatives vector, the "largest" is unclear and could mean e.g., in (-2, -3, -4) that we take -2. In this case the (xj/xi) <= 1 condition would not be true.

**Comment by EricDarve** [comment]
Yes I clarified this. Thanks.
