### ISSUE TITLE
Potential Issue Page 139

### ISSUE THREAD

**Issue by noa-codes** [EricDarve/numerical_linear_algebra#133]
I'm not 100% sure on this one, but I'm confused by the following statement:

> In MGS we interleave STEP 1 and STEP 2: first we project a_j to be orthogonal to q_1, and we fix the **first column** of R. Then we project a_j to be orthogonal to q_2, and fix the **second column** of R, and so on.

Since we're working with a_j and r_j here, aren't we fixing each entry / row of r_j, rather than columns of R?

**Comment by EricDarve** [comment]
You are correct. The book has gone through many revisions and unfortunately this brings in new errors. This text used to be correct! We are updating entries of R in column j, row by row, from 1 to j-1.
