### ISSUE TITLE
Issue with graphic on p152?

### ISSUE THREAD

**Issue by iamsalil** [EricDarve/numerical_linear_algebra#135]
The eigenvalue decomposition on the bottom of page 152 appears to me to not be parallel with the text/bottom of the page. It might be worth checking on but could just be a mistake on my part.

**Comment by EricDarve** [comment]
![image](https://user-images.githubusercontent.com/4644566/67120524-5124be00-f19e-11e9-91b8-dabd6c2847e8.png)

I don't understand your comment. What do you mean by "parallel"? You mean the figure is not straight? It was drawn by hand. The bottom sides of the squares are not exactly horizontal, and the square on the left (matrix A) is slightly higher, but it's pretty small.

**Comment by EricDarve** [comment]
Closing issue
