### ISSUE TITLE
Big-O notation in power iteration, pg 154

### ISSUE THREAD

**Issue by jmhb1** [EricDarve/numerical_linear_algebra#141]
This is extremely pedantic (and possibly incorrect), but in power iteration convergence analysis, pg 154, the exponent, 'k', is placed outside the outer brackets of the O.
![image](https://user-images.githubusercontent.com/22034067/68078979-7ddff480-fd9e-11e9-9824-e63aeec122ee.png)

I had thought the entire expression had to be enclosed by brackets, like in pg 166:
![image](https://user-images.githubusercontent.com/22034067/68078990-9bad5980-fd9e-11e9-864a-3bd6ec37e0ad.png)

**Comment by EricDarve** [comment]
Fixed!
