### ISSUE TITLE
p. 180, implicit Q thm, index

### ISSUE THREAD

**Issue by jsrozner** [EricDarve/numerical_linear_algebra#146]
Just above eq. 6.5, we have
h_ij = u_i' * H * u_j, for i <=j

I think it should be i <= j+1

Consider the previous eq, with the sum, where index runs from i to j+1. We should have j+1 equations. i <= j gives only j equations.

**Comment by jsrozner** [comment]
the final term in the equation, if we take i = j+1 in the sum would be

h_j+1,j = u_j+1 ' * H * u_j

**Comment by jsrozner** [comment]
Ah, I see what has been done: the final term follows below. But technically this equation should still hold for i <= j + 1 since u_j+1 is still orthogonal to all other u_i.

One more note on this problem:

(6.5) claims that the right hand side is completely determined, but the final term in the sum on the right is h_j,j * u_j.

Our assumption for induction was only that h_i,k, k<j is known, so then h_j,j would not be known. I think the assumption should be "Assume that h1_i,k , k <= j .... are given"

**Comment by EricDarve** [comment]
The eqn above 6.5 stops at i = j because i = j+1 involves vectors u_j+1 which is not known.
Really the only thing you need in the induction is u_i, i <= j. Then from u_i^T u_j you get all h_ij. h_j+1,j is just the norm of the vector. So all entries in H are determined from the u's. So the induction is that we know u_i, i <= j, and prove that u_j+1 can be computed.

**Comment by jsrozner** [comment]
Makes sense, it was a little confusing because we are solving for h_ij in the midle, and then solving for h_j+1,j * u_j+1.

Technically the equation that I mentioned at the top does *hold* for j+1, based on the summation in the previous step, but you're right that we don't know its value yet.

It seems like the proof on page 220 for Arnoldi (effectively gram-schmidt with a hessenberg matrix) is basically the same as this proof. The proof on 220 is in some ways nicer, since it has prictures and makes clearer what we do / don't know. 

But basically it's the same math and logic duplicated...just noting it!

**Comment by EricDarve** [comment]
Yes the ideas are essentially the same.
