### ISSUE TITLE
Potential clarification needed pages 219-220

### ISSUE THREAD

**Issue by gradeyw** [EricDarve/numerical_linear_algebra#148]
The sentence "This follows because the columns of Q are orthonormal" seems out of place and unnecessary. The equation shown is just another way to understand Q^T * A * Q = H, where Q, A, and H can be any matrices and should therefore hold regardless of the orthonormality of the columns of Q

![image](https://user-images.githubusercontent.com/55860296/68377214-d3016a80-00fe-11ea-9a40-10a5bcb4df35.png)

I think if the point is that Q^T * A * Q = H can be rewritten as A * Q = Q * H (and vice versa) because Q is an orthogonal matrix (with orthonormal columns), it should go above to the middle of page 219:
![image](https://user-images.githubusercontent.com/55860296/68378102-65563e00-0100-11ea-9899-7a57cf09507e.png)

**Comment by salliewalecka** [comment]
+1 to this, 

I read that line and spent a long time trying to figure out where cancellations of the  orthonormal q_i's took place. Then just realized you are only using the orthogonal nature to put it on the other side and you are just writing out the entry :)   Would have saved me some work.

**Comment by EricDarve** [comment]
Right. This sentence was added recently. The logic does not work here. I changed it. Thanks.
