### ISSUE TITLE
Typo pg 185, 191

### ISSUE THREAD

**Issue by jmhb1** [EricDarve/numerical_linear_algebra#150]
### 1 
pg 185:
> In this case, the shifts will not affect to top eigenvector very much 

Suggest
> In this case, the shifts will not affect the top eigenvector very much 

### 2
pg 191 
> To avoid an infinite loop if convergence fails, we bail out of we reach too many iterations

Suggest:
> To avoid an infinite loop if convergence fails, we bail out if we reach too many iterations

### 3
Also a suggestion that "unreduced" be explicitly defined in relation to Hessenberg matrices. The word is used the first time on pg 179 - theorem 3.1. 
I noticed that lecture notes made a point of defining it (lecture 10).

**Comment by EricDarve** [comment]
Thank you. Good points. +3
