### ISSUE TITLE
183: eigenvalues of block upper triangular

### ISSUE THREAD

**Issue by jsrozner** [EricDarve/numerical_linear_algebra#152]
The purple block is titled "eigenvalues of block upper triangular" but then we write "Let H be an upper hessenberg matrix".

Shouldn't we be doing the proof for a matrix T, upper triangular? Yes H, hessenberg, can be written as a block upper triangular and so the proof for upper triangular holds for upper hessenberg. But as we show in the next purple block, generally we look for a subdiagonal that is 0. In this case, H actually looks like a true upper triangular matrix, in the sense that the subblock H[p+1:n, 1:p] is zero (vs generally for an unreduced H, with H[p+2:n, 1:p] = 0).

**Comment by EricDarve** [comment]
I changed the text and removed upper Hessenberg. This is true in general for any square matrix.

I don't understand the rest of your comment though. H is never upper triangular unless the subdiagonal is entirely zero. Moreover eigenvalues for an upper triangular matrix are trivially along the diagonal so the theorem is not needed.

In the next purple block we only look for a single subdiagonal entry equal to 0. So T_k is still block upper triangular. And (T_k)_11 and (T_k)_22 are both upper Hessenberg.

H[p+1:n, 1:p] = 0 does not mean the matrix is upper triangular.
