### ISSUE TITLE
Defining the subscript on Lambda pg 232

### ISSUE THREAD

**Issue by salliewalecka** [EricDarve/numerical_linear_algebra#153]
<img width="337" alt="Screen Shot 2019-11-07 at 3 08 05 PM" src="https://user-images.githubusercontent.com/11946238/68435598-88b8d180-0170-11ea-9f8b-e70088c64117.png">

I'm not sure the meaning if $\lambda_{1,k}$ in this context.  In the exercise 43 it seems to be the largest eigenvalue of T_k but I couldn't find the definition anywhere in the neighboring pages.

**Comment by EricDarve** [comment]
I added a definition. It's the estimate of lambda_1 produced by the Lanczos iteration at step k.
