### ISSUE TITLE
pg 159 citation not showing correctly 

### ISSUE THREAD

**Issue by salliewalecka** [EricDarve/numerical_linear_algebra#155]
<img width="838" alt="Screen Shot 2019-11-07 at 5 20 00 PM" src="https://user-images.githubusercontent.com/11946238/68441424-e2c29280-0182-11ea-9949-b7689b28c60b.png">

**Comment by salliewalecka** [comment]
pg 151 has it as well, I think its a larger issue with the bibliography

**Comment by EricDarve** [comment]
Sorry. I did not compile the file correctly in the last update.
