### ISSUE TITLE
pg 182 define mu_k in proof box

### ISSUE THREAD

**Issue by salliewalecka** [EricDarve/numerical_linear_algebra#159]
Not sure if this is too nit picky, but for the proof statement, maybe it should mention `and $\mu_k$ is an eigenvalue of T_{k-1}` just so it is more self contained.

<img width="753" alt="182" src="https://user-images.githubusercontent.com/11946238/68486498-096de100-01f6-11ea-8a06-250c3ce55a46.png">

**Comment by EricDarve** [comment]
No you are right. This needs to be stated. I rewrote this problem slightly to make it more general.
