### ISSUE TITLE
p130 - Typo Householder Reflection

### ISSUE THREAD

**Issue by gchhor** [EricDarve/numerical_linear_algebra#16]
"Then Q1.T.a1 should be parallel to e1. Since Q1.T does not change the norm of a1.." **instead of** "Then "Q1.a1 should be parallel to e1. Since Q1 does not change the norm of a1.."

![capture d ecran 2017-10-15 a 17 00 28](https://user-images.githubusercontent.com/32273483/31590734-62ae2a14-b1ca-11e7-956b-3f4675ffa697.png)

**Comment by EricDarve** [comment]
Reported already. Thanks.
