### ISSUE TITLE
p. 228 - why the - in figure for least squares

### ISSUE THREAD

**Issue by jsrozner** [EricDarve/numerical_linear_algebra#160]
Why have -A^k * q_1? (Specifically, why have the -1?)

The problem is equivalent without a -1, from orthogonality? Trefethen's diagram also does not have -1.

**Comment by tifffan** [comment]
If we rewrite the problem of minimizing ||Q_k y + A^k * q_1|| as minimizing ||Ax - b||_2, then b = - A^k * q_1, which is the approximation target in least squares problem. The problem is equivalent in the sense that taking y = -y would solve the least squares problem with b = A^k * q_1.

**Comment by EricDarve** [comment]
Correct answer. +1 to both!
