### ISSUE TITLE
Convergence rates

### ISSUE THREAD

**Issue by shaundatta** [EricDarve/numerical_linear_algebra#162]
The convergence rates for power (p. 154), inverse (p. 155), and orthogonal (p. 166) iterations appear without absolute value signs in the course reader, whereas in all the recitations we have used absolute values. I checked with Leopold; he and I think that these convergence rates should have absolute value signs.

**Comment by EricDarve** [comment]
You are right. I was under the impression that big O implied an absolute value but the term in the big O needs to be positive indeed.
