### ISSUE TITLE
page 185 - minor typo

### ISSUE THREAD

**Issue by ilemhadri** [EricDarve/numerical_linear_algebra#163]
"In this case, the shifts will not affect to top eigenvector very" should be "In this case, the shifts will not affect the top eigenvector very".

As a side note, may I ask what software you are using to generate your beautiful figures?

**Comment by noa-codes** [comment]
#143 :)

**Comment by EricDarve** [comment]
It's a combination of different things. procreate on the ipad is the main tool. Also tikz for latex figures. Some of the figures are done with plotlyjs.
