### ISSUE TITLE
pg 183. Matrix indexing problem

### ISSUE THREAD

**Issue by jmhb1** [EricDarve/numerical_linear_algebra#164]
Pg 183

![image](https://user-images.githubusercontent.com/22034067/68722391-24c84b80-056a-11ea-85e0-cbe72bbdcf79.png)

I think the matrix at the end of that paragraph, `T[1:n-1, n-1]`, should be `T[1:n-1, 1:n-1]`.

**Comment by EricDarve** [comment]
Correct. Thank you!
