### ISSUE TITLE
Eckart-Young

### ISSUE THREAD

**Issue by shaundatta** [EricDarve/numerical_linear_algebra#166]
The final clause of Theorem 5.4, "and moreover B minimizes || A-B ||," ought to include the stipulation "over rank-r matrices." For example, it could read "and moreover C=B minimizes || A-C ||_{2} over rank-r matrices C." As currently stated, one might interpret the minimum to be over all matrices in C^{mxn}, in which case B is not the minimizer.

**Comment by EricDarve** [comment]
Yes. You are right. Poorly stated.
