### ISSUE TITLE
Typo pg 272 + theorem & exercise indexing

### ISSUE THREAD

**Issue by jmhb1** [EricDarve/numerical_linear_algebra#168]
### 1
pg 272
> subspace method which choses 

"choses" should be "chooses"

### 2
Equation on pg 263 has a missing close-bracket on the superscript e^{(0)}
![image](https://user-images.githubusercontent.com/22034067/69368915-e0b30600-0c4f-11ea-9eba-46591ca88478.png)

### 3
Page 291, in the box for convergence of CG method, the first term is the 2-norm of (x-x^k), which is equal to A^{-1} norm of the residual.
![image](https://user-images.githubusercontent.com/22034067/69298049-97b47080-0bc1-11ea-9f42-824947242a26.png)
But earlier, it is defined as the A-norm of (x-x^k)
![image](https://user-images.githubusercontent.com/22034067/69298174-f679ea00-0bc1-11ea-8648-ef384ab6adc1.png)
Which is also how it is in Golub pg 236. 

### 4
This may or may not be a problem, but the numbers that index theorems and exercises are linked to the subsection number, and not the section number (or maybe it's the chapter number). 

So there are two "Theorem 1.1"s: one in section 4.1 and another in 8.1. There are six "Exercise 1.1"s. 
On the other hand, figures are indexed to their section (or chapter).

**Comment by EricDarve** [comment]
Thanks. For (3), it should have been the _A norm ||x-xk||. I am trying to fix the numbering. That's a little more complicated.
