### ISSUE TITLE
A-conjugacy of search directions in CG p. 273

### ISSUE THREAD

**Issue by shaundatta** [EricDarve/numerical_linear_algebra#169]
Since the update vectors are \Delta x^{(k)} and \Delta x^{(l)}, on p. 273 the \Delta in the boxed equation ought to appear within the parenthesis, i.e. \Delta (x^{(k)})^{T} A ... --> (\Delta x^{(k)})^{T} A ..., as in the slides from Lecture 14. 

As currently written, it looks like an A-conjugacy condition on \Delta x^{(l)} and x^{(k)}, not \Delta x^{(k)}.

**Comment by EricDarve** [comment]
Correct. Fixed.
