### ISSUE TITLE
top of pg 270 "unrolling the iteration steps yields solution in krylov subspace"

### ISSUE THREAD

**Issue by salliewalecka** [EricDarve/numerical_linear_algebra#170]
Isn't this only true if our initial guess is `X^(0)=0`?

I kind of remember taking my initial guess for some algorithm to be `x^(0)=b` sometime in undergrad, so if the assumption is that we take `X^(0)=0` it would make more sense to me if it was written down.

**Comment by salliewalecka** [comment]
I think this was mentioned in class, but not certain.

**Comment by EricDarve** [comment]
I am fixing this. Thank you.
