### ISSUE TITLE
pg 277 \mu_{k+1} tells us how much to step in p^{k+1} direction not p^k

### ISSUE THREAD

**Issue by salliewalecka** [EricDarve/numerical_linear_algebra#171]
I think there is a slight typo on the bottom of pg277 and it should read "which tells us how much to step in the `p^{k+1}` direction"

<img width="644" alt="Screen Shot 2019-11-20 at 10 01 52 PM" src="https://user-images.githubusercontent.com/11946238/69311545-664b9d00-0be1-11ea-9969-b83d029c153d.png">

**Comment by EricDarve** [comment]
Yes!
