### ISSUE TITLE
bottom of pg 298 MINRES applies to any symmetric [and non-singular] A

### ISSUE THREAD

**Issue by salliewalecka** [EricDarve/numerical_linear_algebra#175]
In earlier paragraphs you emphasized that the assumption was that A is both symmetric AND non-singular, but you seem to drop it in this sentence.  Not sure if it matters to you or not.

**Comment by EricDarve** [comment]
A needs to be non-singular here as well. In particular to get pk^T A^T A pk > 0. _A_ non-singular is assumed in general for the entire Chapter 9.

I am not seeing where the book says that "In earlier paragraphs you emphasized that the assumption was that A is both symmetric AND non-singular." Where is the non-singular statement?
