### ISSUE TITLE
~296 CR for negative definite symmetric matrix

### ISSUE THREAD

**Issue by salliewalecka** [EricDarve/numerical_linear_algebra#176]
The section of CR is a little confusing as the book says we run into trouble when A is indefinite. Yet, later in the section (and at the intro) we then enforce a being positive definite and never talk about whether it would work for negative definite.  I think it would be worthwhile to add a short sentence saying for simplicity "we assume A is SPD (though a symmetric negative definite will work too)".

**Comment by EricDarve** [comment]
I added negative definite in a few places. p. 298, 300, 301.
