### ISSUE TITLE
Cholesky is LL^T p. 329

### ISSUE THREAD

**Issue by shaundatta** [EricDarve/numerical_linear_algebra#177]
On p. 329, "Recall from Section 5 that Cholesky factorization writes an SPD matrix A as A=L^T L, where L is a lower-triangular matrix with positive entries on the diagonal." To be consistent with the definition on p. 113, this should be LL^T, not L^T L.

**Comment by EricDarve** [comment]
You are correct. The first term L should be lower triangular.
