### ISSUE TITLE
pg 335, Wording of def "non-zero entries if x"

### ISSUE THREAD

**Issue by jmhb1** [EricDarve/numerical_linear_algebra#179]
#1 
pg346 minor typo in julia indexing:
> B = A[k+1:n, k+1,n]

The last comma should be a colon 
> B = A[k+1:n, k+1:n]

#2 
Pg 335, sec 10.3
The following is the definition for the set `X` that may be nonzero in solving a sparse lower-triangular.

![image](https://user-images.githubusercontent.com/22034067/70180709-68a7ff80-1695-11ea-9cfb-042efe8fbd6c.png)

My understanding is that if either A OR B hold, then the element will be in X. 
If that is correct, I suggest that the following is confusing:
> We denote the minimal set so that both (a) and (b) hold by X

And should instead be 
> We denote the minimal set so that either (a) or (b) hold by X

If that is the correct reading, the same change might be worthwhile on pg 343, section 10.4.2 
![image](https://user-images.githubusercontent.com/22034067/70181001-eff57300-1695-11ea-9ec1-b20378374b2f.png)

**Comment by shaundatta** [comment]
I am also confused about #2. x_i could be made nonzero from (a) and (b), and in particular could be nonzero when both (a) and (b) hold. Thus the condition for nonzero entries of x should be an OR and not an XOR. As written, the XOR condition is inconsistent with the statement that "both (a) and (b) hold" for the minimal set X. If the condition were actually an XOR, then the minimal set for which both (a) and (b) hold would be the null set.

**Comment by EricDarve** [comment]
`#1` good catch; thanks.

`#2` There is a slight confusion in understanding. I tried to clarify. There are 2 different points of view.

Say S = A U B. You can say x in S implies (x in A or x in B). That's an or. Or you can say. (x in A implies x in S) and (x in B implies x in S). That's an and. The latter is what we meant in the course reader.

I clarified the text in the two blue boxes you pasted above.
