### ISSUE TITLE
p. 337 - indexing on x_j

### ISSUE THREAD

**Issue by jsrozner** [EricDarve/numerical_linear_algebra#184]
Just above section 4, step 2: "then we run a modified version..."

should we have "we only update x_i for j in X"?  since our alg on page 334 was

for each i > j st L_ij !=0
    x_i = x_i - L_ij * x_j

So we're updating x_i, but only for those x_j where j is in X

**Comment by EricDarve** [comment]
To be consistent it should be either x_j, j in X, or x_i, i in X; your suggestion is a bit confusing. It's correct but the meaning is not obvious. Since we talk about `update` it seems to make more sense to have x_i, i in X.
