### ISSUE TITLE
pg 335 is something missing in the non-zero entries shadowbox

### ISSUE THREAD

**Issue by salliewalecka** [EricDarve/numerical_linear_algebra#186]
<img width="693" alt="Screen Shot 2019-12-05 at 10 10 13 AM" src="https://user-images.githubusercontent.com/11946238/70261622-a9f8e780-1747-11ea-83cc-4d356c4bc0e7.png">

When the reader gets to this shadow box, you haven't introduced X as the graph yet, so the box becomes a little confusing. I'm not sure if there is also another symbol that didn't render, because the last line doesn't makes sense to me.

**Comment by EricDarve** [comment]
I added some more text in that box to clarify. Also someone else had posted another comment about this box.
