### ISSUE TITLE
Maybe stick with (Lp, Lj, Lx) convention or (rowptr, colval, nxval), but not both

### ISSUE THREAD

**Issue by salliewalecka** [EricDarve/numerical_linear_algebra#187]
At risk of being too opinionated :) 

At the beginning of the chapter you introduced the CSR struct with elements (rowptr, colval, nzval), but later (and in the homeworks) you transition to just using a tuple of (Lp, Lj, Lx).  The former is more readable to me, but regardless of which you choose, it would probably make sense to stick with one.

**Comment by EricDarve** [comment]
Yes, I see your point. The (rowptr, colval, nzval) notations come from Julia.

See
https://docs.julialang.org/en/v1/stdlib/SparseArrays/#man-csc-1

So for consistency I should stick with that.
