### ISSUE TITLE
Exercise 4.4 #3 p. 349

### ISSUE THREAD

**Issue by shaundatta** [EricDarve/numerical_linear_algebra#188]
Statement of the problem is, “A vertex i is a leaf in the elimination tree iff there are no edges (i,j) for j<i in G_{ch}.” Based on the algorithm to construct G_ch on p. 343, we only ever introduce edges from lower-numbered nodes to higher-numbered nodes. If I am understanding correctly then, the problem statement should read, “iff there are no edges (j,i) for j<i in G_{ch}.” The property as currently stated, that there are no edges (i,j) for j<i in G_ch, holds for any vertices i in the elimination tree.

**Comment by EricDarve** [comment]
Yes it's j -> i. I rewrote that statement. It's replaced a_{ij} = 0 for j < i.

I think you are viewing an old version of the PDF. Your page number of exercise number are not up to date.
