### ISSUE TITLE
Typo page 286

### ISSUE THREAD

**Issue by noa-codes** [EricDarve/numerical_linear_algebra#189]
In the first paragraph, in the description of Gram-Schmidt, it says 
> "...to find some vector \nu^{(2)} that is A-conjugate to \nu^{(2)}, and so on."

I think this should be
> "...to find some vector \nu^{(2)} that is A-conjugate to \nu^{(1)}, and so on."

Since \nu^{(2)} is not orthogonal to itself.

**Comment by EricDarve** [comment]
That whole section has plenty of errors. Sorry. This is a recent change and the indices are wrong. Let me know if the new text makes more sense.

**Comment by noa-codes** [comment]
The new text does make more sense -- I am a bit confused about why we use k+1 linearly independent vector (nu_0 through nu_k) to create k A-orthogonal vectors (p_1 through p_k). Isn't Gram-Schmidt one-to-one?

**Comment by EricDarve** [comment]
It goes up to p^{(k+1)}. So you have k+1 vectors on both sides.

**Comment by EricDarve** [comment]
I made various updates to indices in that section. There were some errors with mu_k and p_k.
