### ISSUE TITLE
p.285: gradient descent interp of CG

### ISSUE THREAD

**Issue by jsrozner** [EricDarve/numerical_linear_algebra#192]
At the top of p. 285, we have the equation "p_k is A orthog to (x_k+1 -x), for all k)

But this suggests that the relation holds only for p_k and r_k+1. (i.e p_1, r_2; p_2, r_3; etc)

In reality, this relation holds for all p_l and r_k, where l < k. Why make a less strong statement here? 

Also suggest possibly mentioning that x_k+1 - x == -r_k+1 for consistency / continuity with the previous definitions for the reader's benefit.

**Comment by jsrozner** [comment]
(The coursereader is not incorrect, but a stronger statement can be made, and this stronger statement is consistent with what's written in the rest of the chapter)

**Comment by EricDarve** [comment]
I made various updates in that section. There were a lot of errors with indexing. It's mu_{k+1} p_{k+1} instead of mu_k p_k.
