### ISSUE TITLE
Inconsistency pg. 222

### ISSUE THREAD

**Issue by noa-codes** [EricDarve/numerical_linear_algebra#193]
On page 222, the course reader states that Q_k^T A Q_k = H_k, (or equivalently, A Q_k = Q_k H_k) but in class we showed that Q_k H_k + h_{k+1, k} q_{k+1} e_k^T = A Q_k. Is there a reason that we drop the q_{k+1} term here?

**Comment by EricDarve** [comment]
I am not sure where you are seeing this in the course reader. Q_k^T A Q_k = H_k is true but A Q_k = Q_k H_k is not. Qk Qk^T is not I.

**Comment by noa-codes** [comment]
I see, my mistake!
