### ISSUE TITLE
Pg. 284 Small Mistake

### ISSUE THREAD

**Issue by apsk14** [EricDarve/numerical_linear_algebra#195]
At the top of the page 284 in the first paragraph I believe  'to find some vector v2 that is A-conjugate to v2' should instead be  'to find some vector p2 that is A-conjugate to p1' or something along those lines. Also, the diagram below this paragraph should have the v-matrix labeled v(1) - v(k+1) instead of (v0) - v(k) to be consistent with the above paragraph.

-Amit Kohli

**Comment by EricDarve** [comment]
I think you are reading an old version of the course reader. This section has been updated. Can you check the new one?

**Comment by EricDarve** [comment]
The index for v needs to start at 0 to match the residual r0 to rk. The residual starts at 0.

**Comment by apsk14** [comment]
Ah I see! My bad
