### ISSUE TITLE
Linspace deprecated in Julia 1.0

### ISSUE THREAD

**Issue by aefreeman** [EricDarve/numerical_linear_algebra#203]
In the norm ball example (p. 14, figure 3.1), the example code uses `linspace` which has been deprecated in Julia 1.0 in favor of `range`. Replacing `linspace(x,y,z)` with `range(x, stop = y, length = z)` returns the desired results

**Comment by EricDarve** [comment]
I guess you are referring to the Julia code in Chap3/ ? I updated all the Julia code in that folder. This code goes back 3-4 years! Hopefully, everything is in order now.
