### ISSUE TITLE
Typo on page 382

### ISSUE THREAD

**Issue by jg43b** [EricDarve/numerical_linear_algebra#204]
It looks like you have `if-elseif-else` instead of `if-else` on the first line of page 382.

**Comment by jg43b** [comment]
Also, the links to Spencer Lyon's PlotlyJS documentation appear to be broken, e.g., 

* _p. 382:* http://spencerlyon.com/PlotlyJS.jl
* _p. 383:* http://spencerlyon.com/PlotlyJS.jl/#installation
* _p. 384:* http://spencerlyon.com/PlotlyJS.jl/manipulating_plots/#saving-figures

**Comment by EricDarve** [comment]
Thanks for the `spencerlyon` links; they have been fixed.

Regarding your first comment, `if-elseif-else` seems correct; that's what the code demonstrates. Maybe the name of the function `f_if_then_else` could be changed although it seems fine to me.
