### ISSUE TITLE
Typo on Page 33

### ISSUE THREAD

**Issue by milesrb** [EricDarve/numerical_linear_algebra#207]
Hi Prof. Darve, 
The textbook for CME 302 is great so far! I think there might be a slight typo in chapter 3. On page 33, the last sentence reads: "They are very easy to compute with accurately, making them the favorite tool of the numerical analyst." 

However, I think "accurately" should be replaced with "accuracy." 

Thanks, 
Miles

**Comment by EricDarve** [comment]
I rewrote the sentence to remove the ambiguity. The original sentence is correct though. The verb is "compute with" and accurately is the adverb. It means that doing computation with orthogonal matrices typically gives accurate results. But the grammar is twisted.
