### ISSUE TITLE
Page 137: .py notebook?

### ISSUE THREAD

**Issue by fboemer** [EricDarve/numerical_linear_algebra#21]
"The notebook QR_Givens.py shows..."
This seems like the only time there is a ".py" (as well as Exercise 2.1 on the same page) instead of a ".ipynb"

Not a typo per-se, but seems inconsistent with the rest of the book.

Best,
Fabian Boemer

**Comment by EricDarve** [comment]
Thanks. It's hard to synchronize the code and the textbook. The code in the book is not entirely consistent or up to date with the working Julia code.
