### ISSUE TITLE
General Issue: Difficult to determine chapter from an individual page.

### ISSUE THREAD

**Issue by okadak126** [EricDarve/numerical_linear_algebra#212]
I would suggest including the chapter number in the section numbers (i.e. for chapter 4, call sections 4.1, 4.2, 4.3, etc., instead of 1,2,3). If I open the book to an arbitrary page, I have to look for a theorem or figure to determine the chapter (this caused me to read the wrong section on multiple occasions). I would also recommend including the chapter number as a header or footer on each page so it is easier to navigate. This may already be a standard part of the publication process, but I wanted to make sure.

**Comment by EricDarve** [comment]
Excellent point. I will look into that. But that makes perfect sense.

**Comment by EricDarve** [comment]
I made some changes to the PDF. Added Chapter number + title and section number. The section number format is 
[chapter number].[section number]
This matches the reading instructions I give out.
