### ISSUE TITLE
G matrix indexing, pages 71-74

### ISSUE THREAD

**Issue by dlahana** [EricDarve/numerical_linear_algebra#215]
At the bottom of page 71, G_1 matrix elements have two indices, as in (g_i)\_{ii}, but later at the bottom of page 72, G_i matrix elements have one index, as in (g_i)\_{i+1}, which was perhaps supposed to be (g_i)\_{i,i+1}, unless g\_i represents a column now, instead of a matrix as it did previously. This column notation appears to continue through page 74. In short, g\_i is first a matrix element and then a column, and perhaps this could be made more clear using superscript notation to index the G matrices, or through maintaining the two index notation for each (g_i) element.

**Comment by EricDarve** [comment]
I see what you are saying. It's a bit tricky. (g_i)_{i+1,i} is to heavy-handed. That's difficult to read. I am going to keep the notation g_i for column i of G_i. We need it for the next few pages. 

I changed the notations at the bottom of p. 69 to avoid using the notation g_1.

Hopefully, it's a little clearer now.
