### ISSUE TITLE
Givens code

### ISSUE THREAD

**Issue by matteosantama** [EricDarve/numerical_linear_algebra#218]
The Julia code for Given rotations on pg. 133 is missing a couple of `end` statements for the conditionals.

I find the code a bit confusing, and I think it could greatly benefit from type hints. Specifically, it's very unclear to me what the parameters `a` and `b` are. Are these vectors? Do they represent `u_1`, `u_2`?

**Comment by EricDarve** [comment]
Yes, the notation was confusing. I replaced a/b with u1/u2. That matches the notations from the text. Hopefully, it's self-explanatory now.
