### ISSUE TITLE
p153

### ISSUE THREAD

**Issue by yyy910805** [EricDarve/numerical_linear_algebra#22]
The error in the estimated eigenvalue decays at (lambda_2/lambda_1)^2k instead of k?

**Comment by EricDarve** [comment]
I don't understand your comment. Is this this equation?

![image](https://user-images.githubusercontent.com/4644566/32284745-651580cc-bee5-11e7-955a-34455b21aece.png)

**Comment by yyy910805** [comment]
It's "similarly the error in the estimated eigenvalue decays at the same rate". In Trefethen p205 (Theorem 27.1) the exponent becomes 2k for the decay of the difference between the estimated eigenvalue and the true eigenvalue. So I'm not sure which one is correct.

**Comment by EricDarve** [comment]
I see. The course reader refers to the error in the eigenvectors. The decay is in k. However, if A is symmetric, then the error in the eigenvalue decays faster with 2k. This is because the Rayleigh-quotient has a zero gradient at the eigenvalue.
