### ISSUE TITLE
Notation for QR iteration

### ISSUE THREAD

**Issue by Shengbo-Wang** [EricDarve/numerical_linear_algebra#223]
The notation used in section QR iteration is a little confusing to me. We write T = Q^TAQ and A = QR where the Qs mean different things.

**Comment by EricDarve** [comment]
Where did you see this? Are these two notations used at the same time on the same page or section? It's OK to have A = QR in Chapter 5 and T = Q^T A Q in 6.2. These are standard notations. A = Q T Q^H is the Schur decomposition, for example.

**Comment by EricDarve** [comment]
I made some changes to distinguish the matrix Q_k in the iteration algorithms from the Q from the Schur decomposition.
