### ISSUE TITLE
Courant-Fischer Minimax Theorem Proof

### ISSUE THREAD

**Issue by okadak126** [EricDarve/numerical_linear_algebra#224]
On page 153-154, a partial proof of the minimax theorem is provided, but S is taken to be a k-dimensional subspace. 
(1) In the theorem statement, shouldn't it say "the set S that attains the maximum is the **span of the** set of eigenvectors..."?
(2) "y in S" should be the linear combination of the k eigenvectors, but the y* given on page 154 is a linear combination of what appears to be n-k+1 eigenvectors (qk through qn). Should this make more explicit that we are choosing k of these vectors?

**Comment by EricDarve** [comment]
(1) You are correct; span is missing.
(2) I added more info in the proof. $S$ has dimension $k$ and the span of $\{q_k, \ldots, q_n\}$ has dimension $n-k+1$. So their intersection is a subspace of dimension at least 1. y^* is a point in that intersection. Hence the equation.
