### ISSUE TITLE
pg. 154 "r" is used but not defined.

### ISSUE THREAD

**Issue by joshoch7** [EricDarve/numerical_linear_algebra#225]
It says "Let's start by walking through the main ideas for r = 2", but it hasn't yet defined r.

It becomes clear later that r is the number of columns in Q, but I think this should be stated beforehand.
<img width="961" alt="Screen Shot 2020-11-02 at 10 12 18 AM" src="https://user-images.githubusercontent.com/1329476/97897820-4333d380-1cf4-11eb-9d33-bf0d967b6fc4.png">

**Comment by EricDarve** [comment]
Thanks. Yes, the text is not working there. I fixed it.
