### ISSUE TITLE
Page 241, chapter reference

### ISSUE THREAD

**Issue by dlahana** [EricDarve/numerical_linear_algebra#226]
At the top of page 241, the reader points the user to chapter 3 to revisit the Gershgorin Disc Theorem, but that's actually covered in chapter 4. Also, it might be more useful to link directly to the subchapter, rather than the beginning of chapter 4.

**Comment by EricDarve** [comment]
Thank you. Gershgorin is in Chapter 3. It's section 4.4 of Chapter 3. I added a page number reference to make it easier to find.
