### ISSUE TITLE
Krylov Subspace - note on span(Q_k) = span(K_k) 

### ISSUE THREAD

**Issue by martzmer** [EricDarve/numerical_linear_algebra#227]
Just a suggestion, but in the section that shows span(Q_k) = span(K_k) (page 218), it might be worth reminding the reader that this depends on K_k being full column rank, which can be guaranteed only because Arnoldi/Lanczos terminates at a step that ensures this. As a more naive reader, I mistakenly assumed that any Krylov space (i.e. the span of {q1, Aq1, ... } for any arbitrary A and q1) would have this quality, but now I understand it only applies to the Q_k produced when Arnoldi terminates (if I understand this correctly).

**Comment by EricDarve** [comment]
I don't understand your comment. If Arnoldi terminates, we cannot construct Qk beyond that step. And the dimension of Kk becomes constant. You are right that span(Q_k) = span(K_k) implies that Arnoldi was able to run at least until step k. If it terminates earlier, Q_k is not defined. K_k not full rank is very special. You need q1 to be a linear combination of only m < n eigenvectors of A, or q1 needs to be in a stable subspace that is not R^n.
What would you change in the text to clarify your confusion?
