### ISSUE TITLE
Typo on p. 269

### ISSUE THREAD

**Issue by joshoch7** [EricDarve/numerical_linear_algebra#228]
In the "A-conjugacy" blue box...

"that in" should be "that are in"

<img width="903" alt="Screen Shot 2020-11-08 at 10 31 30 AM" src="https://user-images.githubusercontent.com/1329476/98472070-baaeaa80-21ad-11eb-9670-8db5a01f0fc9.png">

**Comment by EricDarve** [comment]
Thanks.
