### ISSUE TITLE
Add more explanations about P152 and P153

### ISSUE THREAD

**Issue by YatongChen** [EricDarve/numerical_linear_algebra#23]
(All of the following potential improvements are based on the discussion with Eric during today's office hour. )
1. P152:
To make it clear, it's better to add more explanations on how we come from equation (6.1) to the next equation:`A^k \approx \lambda_1^k x_1 y_1^T`.
2.  P153: 
After equation 
`A^{k} q^{(0)} = \lambda^k_1 \alpha_1 x_1 +\cdots + \lambda^k_n \alpha_n x_n`,
it's better to add one more line:
=` \lambda^k_1 (\alpha_1 x_1 +(\frac{ \alpha_2}{ \alpha_1})^k x_2   \cdots + (\frac{ \alpha_n}{ \alpha_1})^k x_n)`(like the last equation in the following figure.)
![screen shot 2017-10-23 at 11 29 41 am](https://user-images.githubusercontent.com/23269526/31906250-81fd5ce8-b7e5-11e7-8f02-da93e7b64476.png)

**Comment by EricDarve** [comment]
Thanks. I added more explanation. I need to expand the explanations in many places.
