### ISSUE TITLE
Expression of Krylov space on page 303.

### ISSUE THREAD

**Issue by AlexCHEN-Engineer** [EricDarve/numerical_linear_algebra#230]
Krylov subspace is expressed as K(matrix, #iteration, vector), but all elsewhere are expressed K(matrix, vector, #iteration). Just a small suggestion that they could follow the same convention.
![image](https://user-images.githubusercontent.com/52059011/98785542-9ae7d400-23b1-11eb-901a-fb696995ab72.png)

**Comment by EricDarve** [comment]
Good catch!!
