### ISSUE TITLE
Typo on pg. 318

### ISSUE THREAD

**Issue by joshoch7** [EricDarve/numerical_linear_algebra#231]
I think the index of the r-bar's should be the same as the index of the r. I'm not sure why one is k-1 and the other is k.

<img width="804" alt="Screen Shot 2020-11-14 at 9 42 01 AM" src="https://user-images.githubusercontent.com/1329476/99152252-e3c3b500-265d-11eb-9ab8-574d3715a1e9.png">

**Comment by EricDarve** [comment]
Thank you!
