### ISSUE TITLE
pg. 277 Misplaced parenthesis

### ISSUE THREAD

**Issue by matteosantama** [EricDarve/numerical_linear_algebra#233]
I believe the `(` should be separating `f` and `x` here.

<img width="743" alt="Screen Shot 2020-11-18 at 11 53 03 AM" src="https://user-images.githubusercontent.com/13473688/99580949-f5c29200-2994-11eb-86de-a6750cb0f377.png">

**Comment by EricDarve** [comment]
Correct!
