### ISSUE TITLE
Formula (9.16) on P300

### ISSUE THREAD

**Issue by zhuofanx** [EricDarve/numerical_linear_algebra#234]
Not sure if someone mentioned this before, but I think the first part of formula (9.16) should be "G_k^T \dots G_1^T (\beta_0e_k)", not "G_1 \dots G_k (\beta_0e_k)". 
![P300](https://user-images.githubusercontent.com/71382981/99814609-29174380-2b84-11eb-8723-eea8284da68a.jpg)
and derivations after it should be modified accordingly. Thanks.

**Comment by EricDarve** [comment]
Thanks.

<img width="509" alt="image" src="https://user-images.githubusercontent.com/4644566/99864951-39ff8f00-2b5b-11eb-890b-f61f2995cd2d.png">

<img width="698" alt="image" src="https://user-images.githubusercontent.com/4644566/99864956-3ec44300-2b5b-11eb-8f55-e34de25ea9ca.png">

**Comment by EricDarve** [comment]
Great catch.
