### ISSUE TITLE
Typo Exercise 9.5 on p.295

### ISSUE THREAD

**Issue by slnader** [EricDarve/numerical_linear_algebra#235]
There is a small typo in the green box on p.295: "right hand size" should be "right hand side."

<img width="671" alt="Screen Shot 2020-11-20 at 10 35 50 AM" src="https://user-images.githubusercontent.com/3459643/99837284-339df280-2b1c-11eb-94df-d3850182616d.png">

**Comment by EricDarve** [comment]
Thank you.
