### ISSUE TITLE
V_k not defined in Problem 48, p.320

### ISSUE THREAD

**Issue by slnader** [EricDarve/numerical_linear_algebra#236]
You can guess that V_k = Q_k from Lanczos, but might be good to define it since the rest of the chapter uses Q_k.

<img width="674" alt="Screen Shot 2020-11-20 at 10 41 22 AM" src="https://user-images.githubusercontent.com/3459643/99838237-a491da00-2b1d-11eb-8ffd-71cc840bb5ae.png">

**Comment by EricDarve** [comment]
I fixed the notations; this problem was written years ago and we have changed some of the notations in the meantime.

<img width="704" alt="image" src="https://user-images.githubusercontent.com/4644566/99865161-b646a200-2b5c-11eb-9912-19dcece2c642.png">
