### ISSUE TITLE
Potential Typos in the Course Reader

### ISSUE THREAD

**Issue by liuf9** [EricDarve/numerical_linear_algebra#237]
This is a collection of potential typos found throughout the quarter and some of them might not necessarily be typos (they depend on your decision) and some of them might be mentioned by other students earlier in this quarter or before this academic year, but I follow the current version of Course Reader on Google Drive.

1. Page 21: (Cy)^T x =y^T (C^T x).
<img width="816" alt="Screen Shot 2020-11-20 at 7 20 46 PM" src="https://user-images.githubusercontent.com/55078114/99866401-b5fed480-2b65-11eb-819b-24b56b3e95e0.png">

2. Page 66: strange indentation of updating “z” in the nested for loop (line 7) in trtrsRow.
<img width="581" alt="Screen Shot 2020-11-20 at 7 25 23 PM" src="https://user-images.githubusercontent.com/55078114/99866463-29a0e180-2b66-11eb-849e-4f6fc362a622.png">

3. Page 81: two’s complement definition: b bits represents a number between -2^(b-1) and 2^(b-1) - 1. Otherwise, there are 2^(b + 1) numbers between -2^b and 2^b - 1 and we only have b bits to represent 2^b numbers.
<img width="715" alt="Screen Shot 2020-11-20 at 7 37 15 PM" src="https://user-images.githubusercontent.com/55078114/99866753-adf46400-2b68-11eb-9a9e-13785fe7a212.png">

4. Page 86: note on the top right slightly covers the top edge.
<img width="220" alt="Screen Shot 2020-11-20 at 7 30 13 PM" src="https://user-images.githubusercontent.com/55078114/99866553-f3b02d00-2b66-11eb-9fa5-be2934fcc9bd.png">

5. Page 100: it might be clearer if you would like to set up a terminated entry In the matrix for repetitive values such as -1, ..., -1 or 1, 1, ..., 1 although it is not necessary as all students can infer from this form.
<img width="567" alt="Screen Shot 2020-11-20 at 7 46 06 PM" src="https://user-images.githubusercontent.com/55078114/99866897-efd1da00-2b69-11eb-9984-5d2e884ce081.png">

6. Page 125: x_2^2 + ... + x_n^2 << x_1^2 (lost the second plus sign).
<img width="932" alt="Screen Shot 2020-11-20 at 7 56 13 PM" src="https://user-images.githubusercontent.com/55078114/99866967-8acab400-2b6a-11eb-8eee-4dc2c0df278e.png">

7. Page 187: strange indentation on extracting B (the second piece of Julia code on this page).
<img width="906" alt="Screen Shot 2020-11-20 at 7 59 59 PM" src="https://user-images.githubusercontent.com/55078114/99867059-278d5180-2b6b-11eb-8538-f5705a99aa98.png">

8. Page 259: lost a comma after "since A is SPD...".
<img width="598" alt="Screen Shot 2020-11-20 at 8 02 49 PM" src="https://user-images.githubusercontent.com/55078114/99867109-7aff9f80-2b6b-11eb-813c-f50a1fb88a0e.png">

9. Page 261: as we have discussed in Slack, we might add an absolute value for c_k(mu) (HW8 2.7).
<img width="1046" alt="Screen Shot 2020-11-20 at 8 04 29 PM" src="https://user-images.githubusercontent.com/55078114/99867176-f3fef700-2b6b-11eb-85af-3049bcd4cc35.png">

**Comment by EricDarve** [comment]
1. correct
2. fixed
3. Correct. It's b-1.
4. Thank you.
5. I see what you are saying but I am going to keep the current form. It's a little ambiguous but adding more entries will also make it look more complicated.
6. Fixed
7. Fixed. It's because tabs are 4 spaces in my editor but show up with a different width in the PDF. So depending on whether it's tabs or spaces the indentation is wrong.
8. Added
9. Fixed
