### ISSUE TITLE
Page 45, wrong hint in exercise

### ISSUE THREAD

**Issue by yokilaarora** [EricDarve/numerical_linear_algebra#30]
In Exercise 2.2, shouldn't it be "use A(t) = tB", instead of "use A(t) = exp(tB)", since in the equation we have det(exp A)? 
But then proving starting from det(A) to this equation will not be possible.

**Comment by EricDarve** [comment]
I am not sure what I meant here. I rewrote the hint with T(t). Let me know if there is still a problem here.

**Comment by EricDarve** [comment]
Closing.
