### ISSUE TITLE
Minor typo (row vs rows) page 148

### ISSUE THREAD

**Issue by fboemer** [EricDarve/numerical_linear_algebra#32]
"Σ has zeros in row**s** r + 1 to m" (page 148)
Not sure what is proper gramatically, but it should be consistent throughout the text.
For comparison,

- "R ̃ is m × n and has zeros in rows n + 1 to m." (page 147)
- "the rows r + 1 to n of U will" (page 109, Exercise 4.2)

**Comment by EricDarve** [comment]
Fixed.
