### ISSUE TITLE
bad rendering on pdf page 107

### ISSUE THREAD

**Issue by marcthibault** [EricDarve/numerical_linear_algebra#4]
![capture d ecran 2017-10-03 a 10 42 44](https://user-images.githubusercontent.com/20352515/31139839-a4811e1c-a827-11e7-9dda-59f6a087e9f1.png)

The red boxes end up on the bad rows/columns. Goal was to emphasize last column of L and last row of U.

**Comment by EricDarve** [comment]
Fixed. Thank you.
