### ISSUE TITLE
Typo page 211

### ISSUE THREAD

**Issue by fboemer** [EricDarve/numerical_linear_algebra#40]
The second proof has incorrect equations (far as I can tell). They should read:
![codecogseqn](https://user-images.githubusercontent.com/7935794/32813435-057e6d48-c95f-11e7-8002-d80cce465a29.gif)

**Comment by EricDarve** [comment]
Thanks. Actually it's l = b / (a-b). That's where the mistake was. Then, it matches the other proof.
