### ISSUE TITLE
inconsistent notation on p. 183

### ISSUE THREAD

**Issue by mll-gh** [EricDarve/numerical_linear_algebra#41]
The block singular vector is defined as $q_i$, but when demonstrating how it interacts with the block matrix $B$, the explanation refers to "$x_i$":

"Then $x_i^TBx_i = \pm\sigma_i$."

It should read:

"Then $q_i^TBq_i = \pm\sigma_i$"

for consistency of notation.

--Martin Lindsey

**Comment by EricDarve** [comment]
Thank you. Good catch.
