### ISSUE TITLE
Pg 194

### ISSUE THREAD

**Issue by yaoyn** [EricDarve/numerical_linear_algebra#42]
On the first line of minimizer polynomial, it states "The zeros of pk are our eigenvalue approximations.".

Should it be zero root? or roots? it seems to be confusing what the sentence actually means

**Comment by EricDarve** [comment]
Where is the confusion? This sentence refers to the zeros of the polynomial pk. You can talk about the zeros of a function: all the xs such that f(x) = 0. Zeros are the same as roots.
