### ISSUE TITLE
Typo page 211

### ISSUE THREAD

**Issue by yhl-icme** [EricDarve/numerical_linear_algebra#44]
The denominator in the third equation should be (b-a)
(Since we are considering lambda =lamda(H) = H in the scalar case)

—
Honglin Yuan

**Comment by jvrsgsty** [comment]
You mean it should be (a-b) right? 
Because H = (A-B)^-1 B, then lambda = b/(a-b).
If not, the fourth equation can't follow from the third.

**Comment by EricDarve** [comment]
I fixed this. Thank you. It's a-b on the denominator for lambda.
