### ISSUE TITLE
Mistake on Pg. 209 

### ISSUE THREAD

**Issue by rsikd001** [EricDarve/numerical_linear_algebra#49]
On page 209, at the top when discussing diagonally dominant, does "i" in the statement "for i = 1,2,...n" need to be changed to "j" since we are summing the entries along the ith row from j = 1,...n ?

**Comment by yhl-icme** [comment]
I think the notation is correct here... It means that the inequality holds for every row $i$

**Comment by EricDarve** [comment]
Yes, it's correct. The sum is over j. The equality holds for many i's.
