### ISSUE TITLE
bad rendering on pdf page 109

### ISSUE THREAD

**Issue by marcthibault** [EricDarve/numerical_linear_algebra#5]
![capture d ecran 2017-10-03 a 10 44 33](https://user-images.githubusercontent.com/20352515/31139941-ef92a29a-a827-11e7-9c95-e26a34a7ac0c.png)

Glitch on pdf rendering, red text overlapping the matrix.

**Comment by EricDarve** [comment]
Fixed

**Comment by EricDarve** [comment]
Are you registered on gradescope? I cannot find you.

**Comment by marcthibault** [comment]
Hi,

I do not think I am! What is the 6-character course entry code? I could not find it on piazza. 

Thank you,
Marc THIBAULT

**Comment by EricDarve** [comment]
https://piazza.com/class/j7uq5zuixwp6bw?cid=11
Middle of post

**Comment by marcthibault** [comment]
I am now registered. 
Thank you,
Marc THIBAULT
