### ISSUE TITLE
Clarification Page 229

### ISSUE THREAD

**Issue by jayadevbhaskaran** [EricDarve/numerical_linear_algebra#50]
"After that, the convergence will look like these eigenvalues no longer exist such that the condition number of A is apparently reduced, resulting in faster convergence."

Does this mean that once the well-separated eigenvalues have good estimates, they will no longer contribute (i.e., it will seem like A has a lower condition number), which will then accelerate convergence? 
If so, I think the current phrasing in the course reader seems confusing.

**Comment by EricDarve** [comment]
Yes, your understanding is correct. I will rephrase.
