### ISSUE TITLE
Typo pp11

### ISSUE THREAD

**Issue by wdeaderick** [EricDarve/numerical_linear_algebra#59]
Page 11 reads "A semi-colon indicates that a new row is created". I believe "semi-colon" should be replaced by "comma" as the example that follows creates new rows with commas, and the next page asks the reader to "note the use of a comma for column vectors (or 1D arrays) and semi-colon for matrices."

**Comment by EricDarve** [comment]
Correct. I fixed p. 11. Thanks.
