### ISSUE TITLE
pg 7 should include 'using Pkg' to avoid ERROR: UndefVarError: Pkg not defined

### ISSUE THREAD

**Issue by salliewalecka** [EricDarve/numerical_linear_algebra#60]
On page 7, the instructions call Pkg without loading it.  For someone new to Julia, it would be helpful to include that they need to have `using Pkg`.

```
using Pkg
Pkg.add("IJulia")
```

Also, the Julia installer for Mac actually doesn't put Julia on one's path, so typing `julia` in a terminal will not work automatically in OSX.

**Comment by EricDarve** [comment]
Thanks. I updated this. There is a new package management in Julia actually. So Pkg() is no longer the default syntax. Although it will work.
