### ISSUE TITLE
Julia 1.0 update, p. 18

### ISSUE THREAD

**Issue by sdjespersen** [EricDarve/numerical_linear_algebra#63]
At the bottom of p. 18, the following text appears: 

> The function `eig` returns both:

However, the ensuing code example (p. 19) uses `eigen`. In Julia 1.0, `eigen` appears to be correct, suggesting that the text on p. 18 needs to be changed.

**Comment by EricDarve** [comment]
Thanks. This has been updated. Lots of changes with Julia v1.0.
