### ISSUE TITLE
Course reader page 130 confusion

### ISSUE THREAD

**Issue by HarryEm** [EricDarve/numerical_linear_algebra#69]
At the bottom, should this really refer to getfr.jl, as this is where the code actually lives? of LU_Rank_Revealing.ipynb actually only uses the function.

Thanks!

**Comment by EricDarve** [comment]
I see your point but the julia notebook is what I meant. I am expecting the reader to open the notebook to see the plot. But yes for the code, it's `getfr.jl`.
