### ISSUE TITLE
typo page 168 & 178

### ISSUE THREAD

**Issue by xr-cc** [EricDarve/numerical_linear_algebra#70]
On page 168, the line below the figure, it says that dimension of U_tilde is n*r and dimension of V_tilde is r*m, but from the context, it should be U_tilde of dimension m*r and V_tilde of dimension n*r (so V_tilde_T is r*n).

On page 178, above the code block, it says "x is an eigenvector with Ax = λ", missing an "x" at the end.

**Comment by EricDarve** [comment]
Thanks. I fixed these errors.
