### ISSUE TITLE
Typo about the size of matrices on Page 168

### ISSUE THREAD

**Issue by QiuyeJia** [EricDarve/numerical_linear_algebra#73]
Since A has size m * n. 

 \tilde{U} should have size m*r, 

\tilde{V} should have size n*r (since it should be able to act on  n-dimensional vector x).

**Comment by QiuyeJia** [comment]
Actually I'm not completely sure...  please point out if I'm wrong.......

**Comment by EricDarve** [comment]
You are right. I made the change.
