### ISSUE TITLE
About books

### ISSUE THREAD

**Issue by usd001** [EricDarve/numerical_linear_algebra#77]
In P182, we assume eigenvalues are complex number because we use norm here. As a result, contents following would use conjunct transpose Q^*.

Also, in P187, we use both T and t to represent transpose. I think we could use uniform thing.

Moreover, it seems that all \ref{} do not work. There are only ?? when quote a picture.

**Comment by EricDarve** [comment]
I fixed the issues with transpose and the references.

For ^* that's a bit more complicated. I would have to change all the ^T to ^H. In the end, the algorithms are written for real matrices. So it makes things more complicated and somewhat unnecessary. I am not convinced yet this needs to be changed.

**Comment by EricDarve** [comment]
What's your full name so I can give you points on gradescope?

**Comment by usd001** [comment]
Chunlin Sun. Thank you very much!
