### ISSUE TITLE
Pg 102

### ISSUE THREAD

**Issue by wdeaderick** [EricDarve/numerical_linear_algebra#78]
Minor point, but it might be better to write "blocking consists _of_" instead of "blocking consists _in_"

**Comment by EricDarve** [comment]
I think "consists in" is correct. You would use "consists of" if something was made of many different elements. Here this describes what blocking is. Do you have an example of "consist of" with this meaning?

**Comment by wdeaderick** [comment]
Had no idea "consists in" was ever correct! Learn something new everyday. Sorry for wasting your time
