### ISSUE TITLE
Page 276

### ISSUE THREAD

**Issue by QiuyeJia** [EricDarve/numerical_linear_algebra#81]
I'm not completely sure is this a typo or not:

on the bottom of page 276, it says if and only if 1-\omega-\lambda / ... is an eigenvalue. I think the definition of the eigenvalue should make the sign reverse?  det(MI+X)=0 means -M is an eigenvalue?

However I think the result is still right since there is an issue about the principal branch of the square root. And there is also an +/- sign in the statement of the theorem....So I'm not sure is it a typo or not...

**Comment by EricDarve** [comment]
I clarified this. Basically, both signs are correct so the writing was a bit sloppy here. I tried to clarify the point.
