### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by manon643** [EricDarve/numerical_linear_algebra#88]
It seems to me like there is a typo page 252 of the book (Chapter 7 Section 1). When stating the Arnoldi process, for the first step we should have i<=k instead of i<k as stated in the previous page. 
![image](https://user-images.githubusercontent.com/18661394/48171558-5e101080-e2b1-11e8-9918-8a304a7650c0.png)

**Comment by EricDarve** [comment]
Good catch. Thank you.
