### ISSUE TITLE
Sign Typo on p273

### ISSUE THREAD

**Issue by rahumble** [EricDarve/numerical_linear_algebra#90]
On page 273, you connect SOR with a splitting method and define
```
A = M - N = (1/omega * D - L) - ((1/omega - 1) * D - U).
```
But earlier we defined a splitting method as operating on ```A = M - N = D - L - U```. The sign on ```U``` does not agree between the two.

**Comment by EricDarve** [comment]
Good catch. It should be + U at the end.
